"""adds genre model

Revision ID: 740c30ca5186
Revises: 726596f39075
Create Date: 2025-05-08 06:13:21.109328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740c30ca5186'
down_revision = '726596f39075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre')
    # ### end Alembic commands ###
